import uuid

from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func
from sqlalchemy.orm import DeclarativeBase, MappedColumn, mapped_column


class Base(DeclarativeBase):
    pass


db = SQLAlchemy(model_class=Base)
migrate = Migrate()


def uuid_pk() -> MappedColumn[uuid.UUID]:
    """Primary key whose UUID is generated by Postgres on insert."""
    return mapped_column(primary_key=True, server_default=func.gen_random_uuid())
